// <auto-generated />
namespace MvcOnlineTicariOtomasyon1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class denemeKargo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(denemeKargo));
        
        string IMigrationMetadata.Id
        {
            get { return "202104061217512_denemeKargo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
